version: '3'
services:
  www:
    image: php:apache
    volumes:
      - "./:/var/www/html"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=db_name
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=db_password
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
